apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shipping
  labels:
    app: microservices-demo
    component: shipping
  namespace: sock-shop
spec:
  jobLabel: shipping-metrics
  selector:
    matchLabels:
      app: shipping
  namespaceSelector:
    matchNames:
    - sock-shop
  endpoints:
  - targetPort: 80
    path: /metrics
